ppo:
  num_timesteps: 10000000
  num_evals: 20
  reward_scaling: 1
  episode_length: 1000
  normalize_observations: True
  action_repeat: 1
  unroll_length: 40
  num_minibatches: 24
  num_updates_per_batch: 8
  discounting: 0.997
  learning_rate: 0.0006
  entropy_cost: 0.001
  num_envs: 128
  batch_size: 256
  save_checkpoint_path: '/home/user/bird/logs/ppo_vel2'
  seed: 0

sac:
  num_timesteps: 108643200
  num_evals: 20
  reward_scaling: 5
  episode_length: 1000
  normalize_observations: True
  action_repeat: 1
  discounting: 0.997
  learning_rate: 0.0006
  num_envs: 128
  batch_size: 128
  grad_updates_per_step: 32
  max_devices_per_host: 1
  max_replay_size: 1048576
  min_replay_size: 8192
  checkpoint_logdir: '/home/user/bird/logs/sac_3'
  seed: 1